M48
; DRILL file {KiCad (7.0.0-0)} date Thursday 16 November 2023 at 12:34:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-16T12:34:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X4.3Y-1.7
X4.3Y-1.9756
T2
X3.4071Y-2.6
T0
M30
