M48
; DRILL file {KiCad (7.0.0)} date Sat Feb 25 11:53:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-25T11:53:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X4.9445Y-3.8488
X5.8354Y-4.3685
X6.3327Y-3.8925
T2
X5.4768Y-2.9604
X5.5768Y-2.9604
X5.6768Y-2.96
X5.7768Y-2.9604
T0
M30
