M48
; DRILL file {KiCad (7.0.0)} date Sat Feb 25 11:53:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-25T11:53:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
%
G90
G05
T1
X5.4768Y-2.8604
X5.5768Y-2.86
X5.6768Y-2.8604
X5.7768Y-2.8604
T0
M30
