M48
; DRILL file {KiCad (7.0.0-0)} date Monday 22 May 2023 at 11:06:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-22T11:06:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
%
G90
G05
T1
X6.65Y-4.0309
X6.75Y-4.0309
X7.0Y-4.0309
X7.1Y-4.0309
T0
M30
