M48
; DRILL file {KiCad (6.0.0)} date Wed May 18 17:52:34 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-18T17:52:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X128.89Y-101.715
X128.89Y-106.565
T2
X125.86Y-101.415
X125.86Y-106.865
T0
M30
