M48
; DRILL file {KiCad (6.0.0-0)} date 2022 June 20, Monday 09:51:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-20T09:51:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X180.655Y-83.82
X180.655Y-111.76
X187.655Y-83.82
X187.655Y-111.76
T0
M30
